"""TOTP (RFC 6238) secret generation, provisioning URL, and verification.

Stdlib-only HMAC; no third-party OTP library. The algorithm is small,
the spec is stable, and we want zero new attack surface in a security
feature.

Parameters fixed for universal authenticator-app compatibility:
- Hash: SHA-1 (every authenticator app accepts this).
- Digits: 6.
- Period: 30 seconds.

See ``docs/MFA-DESIGN.md`` for the rationale.
"""

from __future__ import annotations

import base64
import hmac
import secrets
import struct
import time
from hashlib import sha1
from urllib.parse import quote, urlencode

#: TOTP step in seconds (RFC 6238 §4 -- universal default).
TOTP_STEP_SECONDS = 30

#: Number of digits in the resulting code (RFC 6238 §5.3).
TOTP_DIGITS = 6

#: Raw secret length in bytes. 20 bytes / 160 bits matches the SHA-1
#: block size and is the RFC 6238 recommendation.
SECRET_BYTES = 20


def generate_totp_secret() -> bytes:
    """Return a fresh 20-byte random TOTP secret."""
    return secrets.token_bytes(SECRET_BYTES)


def secret_to_base32(secret: bytes) -> str:
    """Render a raw secret as RFC 4648 base32 (no padding) for QR codes."""
    return base64.b32encode(secret).rstrip(b"=").decode("ascii")


def provisioning_url(
    *,
    secret: bytes,
    account_label: str,
    issuer: str,
) -> str:
    """Build the ``otpauth://totp/...`` URL that authenticator apps scan.

    Args:
        secret: Raw TOTP secret (NOT the base32 form).
        account_label: User-visible account identifier; conventionally
            the user's email.
        issuer: Service name shown by the authenticator app.
            Conventionally ``z4j (<host>)``.

    The returned URL is RFC-style ``otpauth://totp/{issuer}:{account}?...``
    with the secret base32-encoded and ``algorithm=SHA1&digits=6&period=30``
    explicitly set. Apps that ignore the explicit params fall back to
    the same defaults, so the URL is universally readable.
    """
    label = f"{issuer}:{account_label}"
    params = {
        "secret": secret_to_base32(secret),
        "issuer": issuer,
        "algorithm": "SHA1",
        "digits": str(TOTP_DIGITS),
        "period": str(TOTP_STEP_SECONDS),
    }
    return f"otpauth://totp/{quote(label, safe='')}?{urlencode(params)}"


def _hotp(secret: bytes, counter: int) -> str:
    """RFC 4226 HOTP value for a given counter."""
    counter_bytes = struct.pack(">Q", counter)
    digest = hmac.new(secret, counter_bytes, sha1).digest()
    offset = digest[-1] & 0x0F
    truncated = (
        (digest[offset] & 0x7F) << 24
        | (digest[offset + 1] & 0xFF) << 16
        | (digest[offset + 2] & 0xFF) << 8
        | (digest[offset + 3] & 0xFF)
    )
    return str(truncated % (10 ** TOTP_DIGITS)).zfill(TOTP_DIGITS)


def current_totp_code(secret: bytes, *, at_time: float | None = None) -> str:
    """Return the TOTP code valid right now (or at the supplied time).

    Useful for tests and for the dashboard's "show me the code I'd
    type next" affordance (not currently used; the dashboard always
    asks the user for their code).
    """
    t = time.time() if at_time is None else at_time
    counter = int(t // TOTP_STEP_SECONDS)
    return _hotp(secret, counter)


def verify_totp_code(
    secret: bytes,
    code: str,
    *,
    at_time: float | None = None,
) -> bool:
    """Verify a 6-digit TOTP code against the secret.

    Accepts a one-step skew on either side of the current 30s window
    (so a code typed within roughly the last 30s OR generated by a
    clock 30s ahead still verifies). Constant-time string compare to
    avoid timing oracles.
    """
    code = code.strip()
    if len(code) != TOTP_DIGITS or not code.isdigit():
        return False

    t = time.time() if at_time is None else at_time
    base_counter = int(t // TOTP_STEP_SECONDS)
    for delta in (-1, 0, 1):
        candidate = _hotp(secret, base_counter + delta)
        if hmac.compare_digest(candidate, code):
            return True
    return False


__all__ = [
    "SECRET_BYTES",
    "TOTP_DIGITS",
    "TOTP_STEP_SECONDS",
    "current_totp_code",
    "generate_totp_secret",
    "provisioning_url",
    "secret_to_base32",
    "verify_totp_code",
]
