/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as LoginMfaRouteImport } from './routes/login_.mfa'
import { Route as AuthenticatedAdminSchedulersRouteImport } from './routes/_authenticated.admin.schedulers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedProjectsSlugRouteImport } from './routes/_authenticated.projects.$slug'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated.settings.account'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated.settings.api-keys'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated.settings.appearance'
import { Route as AuthenticatedSettingsChannelsRouteImport } from './routes/_authenticated.settings.channels'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated.settings.general'
import { Route as AuthenticatedSettingsMembershipsRouteImport } from './routes/_authenticated.settings.memberships'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated.settings.notifications'
import { Route as AuthenticatedSettingsProjectsRouteImport } from './routes/_authenticated.settings.projects'
import { Route as AuthenticatedSettingsRuntimeRouteImport } from './routes/_authenticated.settings.runtime'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated.settings.security'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated.settings.system'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'
import { Route as AuthenticatedProjectsSlugIndexRouteImport } from './routes/_authenticated.projects.$slug.index'
import { Route as AuthenticatedProjectsSlugAgentsRouteImport } from './routes/_authenticated.projects.$slug.agents'
import { Route as AuthenticatedProjectsSlugAuditRouteImport } from './routes/_authenticated.projects.$slug.audit'
import { Route as AuthenticatedProjectsSlugAutomationRouteImport } from './routes/_authenticated.projects.$slug.automation'
import { Route as AuthenticatedProjectsSlugCommandsRouteImport } from './routes/_authenticated.projects.$slug.commands'
import { Route as AuthenticatedProjectsSlugIssuesRouteImport } from './routes/_authenticated.projects.$slug.issues'
import { Route as AuthenticatedProjectsSlugQueuesRouteImport } from './routes/_authenticated.projects.$slug.queues'
import { Route as AuthenticatedProjectsSlugSchedulesRouteImport } from './routes/_authenticated.projects.$slug.schedules'
import { Route as AuthenticatedProjectsSlugSettingsRouteImport } from './routes/_authenticated.projects.$slug.settings'
import { Route as AuthenticatedProjectsSlugTasksRouteImport } from './routes/_authenticated.projects.$slug.tasks'
import { Route as AuthenticatedProjectsSlugTrendsRouteImport } from './routes/_authenticated.projects.$slug.trends'
import { Route as AuthenticatedProjectsSlugWorkersRouteImport } from './routes/_authenticated.projects.$slug.workers'
import { Route as AuthenticatedSettingsNotificationsIndexRouteImport } from './routes/_authenticated.settings.notifications.index'
import { Route as AuthenticatedSettingsNotificationsChannelsRouteImport } from './routes/_authenticated.settings.notifications.channels'
import { Route as AuthenticatedSettingsNotificationsDeliveriesRouteImport } from './routes/_authenticated.settings.notifications.deliveries'
import { Route as AuthenticatedSettingsNotificationsSubscriptionsRouteImport } from './routes/_authenticated.settings.notifications.subscriptions'
import { Route as AuthenticatedProjectsSlugSchedulesScheduleIdRouteImport } from './routes/_authenticated.projects.$slug.schedules_.$scheduleId'
import { Route as AuthenticatedProjectsSlugSchedulesReconcileRouteImport } from './routes/_authenticated.projects.$slug.schedules_.reconcile'
import { Route as AuthenticatedProjectsSlugSettingsIndexRouteImport } from './routes/_authenticated.projects.$slug.settings.index'
import { Route as AuthenticatedProjectsSlugSettingsDefaultsRouteImport } from './routes/_authenticated.projects.$slug.settings.defaults'
import { Route as AuthenticatedProjectsSlugSettingsDeliveriesRouteImport } from './routes/_authenticated.projects.$slug.settings.deliveries'
import { Route as AuthenticatedProjectsSlugSettingsMembersRouteImport } from './routes/_authenticated.projects.$slug.settings.members'
import { Route as AuthenticatedProjectsSlugSettingsNotificationsRouteImport } from './routes/_authenticated.projects.$slug.settings.notifications'
import { Route as AuthenticatedProjectsSlugSettingsProvidersRouteImport } from './routes/_authenticated.projects.$slug.settings.providers'
import { Route as AuthenticatedProjectsSlugWorkersWorkerIdRouteImport } from './routes/_authenticated.projects.$slug.workers_.$workerId'
import { Route as AuthenticatedProjectsSlugSettingsNotificationsIndexRouteImport } from './routes/_authenticated.projects.$slug.settings.notifications.index'
import { Route as AuthenticatedProjectsSlugSettingsNotificationsChannelsRouteImport } from './routes/_authenticated.projects.$slug.settings.notifications.channels'
import { Route as AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRouteImport } from './routes/_authenticated.projects.$slug.settings.notifications.deliveries'
import { Route as AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRouteImport } from './routes/_authenticated.projects.$slug.settings.notifications.subscriptions'
import { Route as AuthenticatedProjectsSlugTasksEngineTaskIdRouteImport } from './routes/_authenticated.projects.$slug.tasks_.$engine.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/login_/mfa',
  path: '/login/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSchedulersRoute =
  AuthenticatedAdminSchedulersRouteImport.update({
    id: '/admin/schedulers',
    path: '/admin/schedulers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsSlugRoute =
  AuthenticatedProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChannelsRoute =
  AuthenticatedSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMembershipsRoute =
  AuthenticatedSettingsMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProjectsRoute =
  AuthenticatedSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRuntimeRoute =
  AuthenticatedSettingsRuntimeRouteImport.update({
    id: '/runtime',
    path: '/runtime',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugIndexRoute =
  AuthenticatedProjectsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugAgentsRoute =
  AuthenticatedProjectsSlugAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugAuditRoute =
  AuthenticatedProjectsSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugAutomationRoute =
  AuthenticatedProjectsSlugAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugCommandsRoute =
  AuthenticatedProjectsSlugCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugIssuesRoute =
  AuthenticatedProjectsSlugIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugQueuesRoute =
  AuthenticatedProjectsSlugQueuesRouteImport.update({
    id: '/queues',
    path: '/queues',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSchedulesRoute =
  AuthenticatedProjectsSlugSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsRoute =
  AuthenticatedProjectsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugTasksRoute =
  AuthenticatedProjectsSlugTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugTrendsRoute =
  AuthenticatedProjectsSlugTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugWorkersRoute =
  AuthenticatedProjectsSlugWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedSettingsNotificationsIndexRoute =
  AuthenticatedSettingsNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsNotificationsRoute,
  } as any)
const AuthenticatedSettingsNotificationsChannelsRoute =
  AuthenticatedSettingsNotificationsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedSettingsNotificationsRoute,
  } as any)
const AuthenticatedSettingsNotificationsDeliveriesRoute =
  AuthenticatedSettingsNotificationsDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedSettingsNotificationsRoute,
  } as any)
const AuthenticatedSettingsNotificationsSubscriptionsRoute =
  AuthenticatedSettingsNotificationsSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedSettingsNotificationsRoute,
  } as any)
const AuthenticatedProjectsSlugSchedulesScheduleIdRoute =
  AuthenticatedProjectsSlugSchedulesScheduleIdRouteImport.update({
    id: '/schedules_/$scheduleId',
    path: '/schedules/$scheduleId',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSchedulesReconcileRoute =
  AuthenticatedProjectsSlugSchedulesReconcileRouteImport.update({
    id: '/schedules_/reconcile',
    path: '/schedules/reconcile',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsIndexRoute =
  AuthenticatedProjectsSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsDefaultsRoute =
  AuthenticatedProjectsSlugSettingsDefaultsRouteImport.update({
    id: '/defaults',
    path: '/defaults',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsDeliveriesRoute =
  AuthenticatedProjectsSlugSettingsDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsMembersRoute =
  AuthenticatedProjectsSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsNotificationsRoute =
  AuthenticatedProjectsSlugSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsProvidersRoute =
  AuthenticatedProjectsSlugSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsRoute,
  } as any)
const AuthenticatedProjectsSlugWorkersWorkerIdRoute =
  AuthenticatedProjectsSlugWorkersWorkerIdRouteImport.update({
    id: '/workers_/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsNotificationsIndexRoute =
  AuthenticatedProjectsSlugSettingsNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsNotificationsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute =
  AuthenticatedProjectsSlugSettingsNotificationsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsNotificationsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute =
  AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedProjectsSlugSettingsNotificationsRoute,
  } as any)
const AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute =
  AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRouteImport.update(
    {
      id: '/subscriptions',
      path: '/subscriptions',
      getParentRoute: () => AuthenticatedProjectsSlugSettingsNotificationsRoute,
    } as any,
  )
const AuthenticatedProjectsSlugTasksEngineTaskIdRoute =
  AuthenticatedProjectsSlugTasksEngineTaskIdRouteImport.update({
    id: '/tasks_/$engine/$taskId',
    path: '/tasks/$engine/$taskId',
    getParentRoute: () => AuthenticatedProjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/account': typeof AuthenticatedAccountRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/login/mfa': typeof LoginMfaRoute
  '/admin/schedulers': typeof AuthenticatedAdminSchedulersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/projects/$slug': typeof AuthenticatedProjectsSlugRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/channels': typeof AuthenticatedSettingsChannelsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/memberships': typeof AuthenticatedSettingsMembershipsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRouteWithChildren
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings/runtime': typeof AuthenticatedSettingsRuntimeRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/projects/$slug/agents': typeof AuthenticatedProjectsSlugAgentsRoute
  '/projects/$slug/audit': typeof AuthenticatedProjectsSlugAuditRoute
  '/projects/$slug/automation': typeof AuthenticatedProjectsSlugAutomationRoute
  '/projects/$slug/commands': typeof AuthenticatedProjectsSlugCommandsRoute
  '/projects/$slug/issues': typeof AuthenticatedProjectsSlugIssuesRoute
  '/projects/$slug/queues': typeof AuthenticatedProjectsSlugQueuesRoute
  '/projects/$slug/schedules': typeof AuthenticatedProjectsSlugSchedulesRoute
  '/projects/$slug/settings': typeof AuthenticatedProjectsSlugSettingsRouteWithChildren
  '/projects/$slug/tasks': typeof AuthenticatedProjectsSlugTasksRoute
  '/projects/$slug/trends': typeof AuthenticatedProjectsSlugTrendsRoute
  '/projects/$slug/workers': typeof AuthenticatedProjectsSlugWorkersRoute
  '/settings/notifications/channels': typeof AuthenticatedSettingsNotificationsChannelsRoute
  '/settings/notifications/deliveries': typeof AuthenticatedSettingsNotificationsDeliveriesRoute
  '/settings/notifications/subscriptions': typeof AuthenticatedSettingsNotificationsSubscriptionsRoute
  '/projects/$slug/': typeof AuthenticatedProjectsSlugIndexRoute
  '/settings/notifications/': typeof AuthenticatedSettingsNotificationsIndexRoute
  '/projects/$slug/schedules/$scheduleId': typeof AuthenticatedProjectsSlugSchedulesScheduleIdRoute
  '/projects/$slug/schedules/reconcile': typeof AuthenticatedProjectsSlugSchedulesReconcileRoute
  '/projects/$slug/settings/defaults': typeof AuthenticatedProjectsSlugSettingsDefaultsRoute
  '/projects/$slug/settings/deliveries': typeof AuthenticatedProjectsSlugSettingsDeliveriesRoute
  '/projects/$slug/settings/members': typeof AuthenticatedProjectsSlugSettingsMembersRoute
  '/projects/$slug/settings/notifications': typeof AuthenticatedProjectsSlugSettingsNotificationsRouteWithChildren
  '/projects/$slug/settings/providers': typeof AuthenticatedProjectsSlugSettingsProvidersRoute
  '/projects/$slug/workers/$workerId': typeof AuthenticatedProjectsSlugWorkersWorkerIdRoute
  '/projects/$slug/settings/': typeof AuthenticatedProjectsSlugSettingsIndexRoute
  '/projects/$slug/settings/notifications/channels': typeof AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute
  '/projects/$slug/settings/notifications/deliveries': typeof AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute
  '/projects/$slug/settings/notifications/subscriptions': typeof AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute
  '/projects/$slug/tasks/$engine/$taskId': typeof AuthenticatedProjectsSlugTasksEngineTaskIdRoute
  '/projects/$slug/settings/notifications/': typeof AuthenticatedProjectsSlugSettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/account': typeof AuthenticatedAccountRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login/mfa': typeof LoginMfaRoute
  '/admin/schedulers': typeof AuthenticatedAdminSchedulersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/channels': typeof AuthenticatedSettingsChannelsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/memberships': typeof AuthenticatedSettingsMembershipsRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings/runtime': typeof AuthenticatedSettingsRuntimeRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/projects/$slug/agents': typeof AuthenticatedProjectsSlugAgentsRoute
  '/projects/$slug/audit': typeof AuthenticatedProjectsSlugAuditRoute
  '/projects/$slug/automation': typeof AuthenticatedProjectsSlugAutomationRoute
  '/projects/$slug/commands': typeof AuthenticatedProjectsSlugCommandsRoute
  '/projects/$slug/issues': typeof AuthenticatedProjectsSlugIssuesRoute
  '/projects/$slug/queues': typeof AuthenticatedProjectsSlugQueuesRoute
  '/projects/$slug/schedules': typeof AuthenticatedProjectsSlugSchedulesRoute
  '/projects/$slug/tasks': typeof AuthenticatedProjectsSlugTasksRoute
  '/projects/$slug/trends': typeof AuthenticatedProjectsSlugTrendsRoute
  '/projects/$slug/workers': typeof AuthenticatedProjectsSlugWorkersRoute
  '/settings/notifications/channels': typeof AuthenticatedSettingsNotificationsChannelsRoute
  '/settings/notifications/deliveries': typeof AuthenticatedSettingsNotificationsDeliveriesRoute
  '/settings/notifications/subscriptions': typeof AuthenticatedSettingsNotificationsSubscriptionsRoute
  '/projects/$slug': typeof AuthenticatedProjectsSlugIndexRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsIndexRoute
  '/projects/$slug/schedules/$scheduleId': typeof AuthenticatedProjectsSlugSchedulesScheduleIdRoute
  '/projects/$slug/schedules/reconcile': typeof AuthenticatedProjectsSlugSchedulesReconcileRoute
  '/projects/$slug/settings/defaults': typeof AuthenticatedProjectsSlugSettingsDefaultsRoute
  '/projects/$slug/settings/deliveries': typeof AuthenticatedProjectsSlugSettingsDeliveriesRoute
  '/projects/$slug/settings/members': typeof AuthenticatedProjectsSlugSettingsMembersRoute
  '/projects/$slug/settings/providers': typeof AuthenticatedProjectsSlugSettingsProvidersRoute
  '/projects/$slug/workers/$workerId': typeof AuthenticatedProjectsSlugWorkersWorkerIdRoute
  '/projects/$slug/settings': typeof AuthenticatedProjectsSlugSettingsIndexRoute
  '/projects/$slug/settings/notifications/channels': typeof AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute
  '/projects/$slug/settings/notifications/deliveries': typeof AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute
  '/projects/$slug/settings/notifications/subscriptions': typeof AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute
  '/projects/$slug/tasks/$engine/$taskId': typeof AuthenticatedProjectsSlugTasksEngineTaskIdRoute
  '/projects/$slug/settings/notifications': typeof AuthenticatedProjectsSlugSettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/login_/mfa': typeof LoginMfaRoute
  '/_authenticated/admin/schedulers': typeof AuthenticatedAdminSchedulersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/projects/$slug': typeof AuthenticatedProjectsSlugRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/channels': typeof AuthenticatedSettingsChannelsRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/memberships': typeof AuthenticatedSettingsMembershipsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRouteWithChildren
  '/_authenticated/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/_authenticated/settings/runtime': typeof AuthenticatedSettingsRuntimeRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/projects/$slug/agents': typeof AuthenticatedProjectsSlugAgentsRoute
  '/_authenticated/projects/$slug/audit': typeof AuthenticatedProjectsSlugAuditRoute
  '/_authenticated/projects/$slug/automation': typeof AuthenticatedProjectsSlugAutomationRoute
  '/_authenticated/projects/$slug/commands': typeof AuthenticatedProjectsSlugCommandsRoute
  '/_authenticated/projects/$slug/issues': typeof AuthenticatedProjectsSlugIssuesRoute
  '/_authenticated/projects/$slug/queues': typeof AuthenticatedProjectsSlugQueuesRoute
  '/_authenticated/projects/$slug/schedules': typeof AuthenticatedProjectsSlugSchedulesRoute
  '/_authenticated/projects/$slug/settings': typeof AuthenticatedProjectsSlugSettingsRouteWithChildren
  '/_authenticated/projects/$slug/tasks': typeof AuthenticatedProjectsSlugTasksRoute
  '/_authenticated/projects/$slug/trends': typeof AuthenticatedProjectsSlugTrendsRoute
  '/_authenticated/projects/$slug/workers': typeof AuthenticatedProjectsSlugWorkersRoute
  '/_authenticated/settings/notifications/channels': typeof AuthenticatedSettingsNotificationsChannelsRoute
  '/_authenticated/settings/notifications/deliveries': typeof AuthenticatedSettingsNotificationsDeliveriesRoute
  '/_authenticated/settings/notifications/subscriptions': typeof AuthenticatedSettingsNotificationsSubscriptionsRoute
  '/_authenticated/projects/$slug/': typeof AuthenticatedProjectsSlugIndexRoute
  '/_authenticated/settings/notifications/': typeof AuthenticatedSettingsNotificationsIndexRoute
  '/_authenticated/projects/$slug/schedules_/$scheduleId': typeof AuthenticatedProjectsSlugSchedulesScheduleIdRoute
  '/_authenticated/projects/$slug/schedules_/reconcile': typeof AuthenticatedProjectsSlugSchedulesReconcileRoute
  '/_authenticated/projects/$slug/settings/defaults': typeof AuthenticatedProjectsSlugSettingsDefaultsRoute
  '/_authenticated/projects/$slug/settings/deliveries': typeof AuthenticatedProjectsSlugSettingsDeliveriesRoute
  '/_authenticated/projects/$slug/settings/members': typeof AuthenticatedProjectsSlugSettingsMembersRoute
  '/_authenticated/projects/$slug/settings/notifications': typeof AuthenticatedProjectsSlugSettingsNotificationsRouteWithChildren
  '/_authenticated/projects/$slug/settings/providers': typeof AuthenticatedProjectsSlugSettingsProvidersRoute
  '/_authenticated/projects/$slug/workers_/$workerId': typeof AuthenticatedProjectsSlugWorkersWorkerIdRoute
  '/_authenticated/projects/$slug/settings/': typeof AuthenticatedProjectsSlugSettingsIndexRoute
  '/_authenticated/projects/$slug/settings/notifications/channels': typeof AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute
  '/_authenticated/projects/$slug/settings/notifications/deliveries': typeof AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute
  '/_authenticated/projects/$slug/settings/notifications/subscriptions': typeof AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute
  '/_authenticated/projects/$slug/tasks_/$engine/$taskId': typeof AuthenticatedProjectsSlugTasksEngineTaskIdRoute
  '/_authenticated/projects/$slug/settings/notifications/': typeof AuthenticatedProjectsSlugSettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/login'
    | '/reset'
    | '/account'
    | '/activity'
    | '/home'
    | '/settings'
    | '/login/mfa'
    | '/admin/schedulers'
    | '/admin/users'
    | '/projects/$slug'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/general'
    | '/settings/memberships'
    | '/settings/notifications'
    | '/settings/projects'
    | '/settings/runtime'
    | '/settings/security'
    | '/settings/system'
    | '/settings/users'
    | '/settings/'
    | '/projects/$slug/agents'
    | '/projects/$slug/audit'
    | '/projects/$slug/automation'
    | '/projects/$slug/commands'
    | '/projects/$slug/issues'
    | '/projects/$slug/queues'
    | '/projects/$slug/schedules'
    | '/projects/$slug/settings'
    | '/projects/$slug/tasks'
    | '/projects/$slug/trends'
    | '/projects/$slug/workers'
    | '/settings/notifications/channels'
    | '/settings/notifications/deliveries'
    | '/settings/notifications/subscriptions'
    | '/projects/$slug/'
    | '/settings/notifications/'
    | '/projects/$slug/schedules/$scheduleId'
    | '/projects/$slug/schedules/reconcile'
    | '/projects/$slug/settings/defaults'
    | '/projects/$slug/settings/deliveries'
    | '/projects/$slug/settings/members'
    | '/projects/$slug/settings/notifications'
    | '/projects/$slug/settings/providers'
    | '/projects/$slug/workers/$workerId'
    | '/projects/$slug/settings/'
    | '/projects/$slug/settings/notifications/channels'
    | '/projects/$slug/settings/notifications/deliveries'
    | '/projects/$slug/settings/notifications/subscriptions'
    | '/projects/$slug/tasks/$engine/$taskId'
    | '/projects/$slug/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/login'
    | '/reset'
    | '/account'
    | '/activity'
    | '/home'
    | '/login/mfa'
    | '/admin/schedulers'
    | '/admin/users'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/general'
    | '/settings/memberships'
    | '/settings/projects'
    | '/settings/runtime'
    | '/settings/security'
    | '/settings/system'
    | '/settings/users'
    | '/settings'
    | '/projects/$slug/agents'
    | '/projects/$slug/audit'
    | '/projects/$slug/automation'
    | '/projects/$slug/commands'
    | '/projects/$slug/issues'
    | '/projects/$slug/queues'
    | '/projects/$slug/schedules'
    | '/projects/$slug/tasks'
    | '/projects/$slug/trends'
    | '/projects/$slug/workers'
    | '/settings/notifications/channels'
    | '/settings/notifications/deliveries'
    | '/settings/notifications/subscriptions'
    | '/projects/$slug'
    | '/settings/notifications'
    | '/projects/$slug/schedules/$scheduleId'
    | '/projects/$slug/schedules/reconcile'
    | '/projects/$slug/settings/defaults'
    | '/projects/$slug/settings/deliveries'
    | '/projects/$slug/settings/members'
    | '/projects/$slug/settings/providers'
    | '/projects/$slug/workers/$workerId'
    | '/projects/$slug/settings'
    | '/projects/$slug/settings/notifications/channels'
    | '/projects/$slug/settings/notifications/deliveries'
    | '/projects/$slug/settings/notifications/subscriptions'
    | '/projects/$slug/tasks/$engine/$taskId'
    | '/projects/$slug/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/invite'
    | '/login'
    | '/reset'
    | '/_authenticated/account'
    | '/_authenticated/activity'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/login_/mfa'
    | '/_authenticated/admin/schedulers'
    | '/_authenticated/admin/users'
    | '/_authenticated/projects/$slug'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/channels'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/memberships'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/projects'
    | '/_authenticated/settings/runtime'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/'
    | '/_authenticated/projects/$slug/agents'
    | '/_authenticated/projects/$slug/audit'
    | '/_authenticated/projects/$slug/automation'
    | '/_authenticated/projects/$slug/commands'
    | '/_authenticated/projects/$slug/issues'
    | '/_authenticated/projects/$slug/queues'
    | '/_authenticated/projects/$slug/schedules'
    | '/_authenticated/projects/$slug/settings'
    | '/_authenticated/projects/$slug/tasks'
    | '/_authenticated/projects/$slug/trends'
    | '/_authenticated/projects/$slug/workers'
    | '/_authenticated/settings/notifications/channels'
    | '/_authenticated/settings/notifications/deliveries'
    | '/_authenticated/settings/notifications/subscriptions'
    | '/_authenticated/projects/$slug/'
    | '/_authenticated/settings/notifications/'
    | '/_authenticated/projects/$slug/schedules_/$scheduleId'
    | '/_authenticated/projects/$slug/schedules_/reconcile'
    | '/_authenticated/projects/$slug/settings/defaults'
    | '/_authenticated/projects/$slug/settings/deliveries'
    | '/_authenticated/projects/$slug/settings/members'
    | '/_authenticated/projects/$slug/settings/notifications'
    | '/_authenticated/projects/$slug/settings/providers'
    | '/_authenticated/projects/$slug/workers_/$workerId'
    | '/_authenticated/projects/$slug/settings/'
    | '/_authenticated/projects/$slug/settings/notifications/channels'
    | '/_authenticated/projects/$slug/settings/notifications/deliveries'
    | '/_authenticated/projects/$slug/settings/notifications/subscriptions'
    | '/_authenticated/projects/$slug/tasks_/$engine/$taskId'
    | '/_authenticated/projects/$slug/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  LoginMfaRoute: typeof LoginMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login_/mfa': {
      id: '/login_/mfa'
      path: '/login/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/schedulers': {
      id: '/_authenticated/admin/schedulers'
      path: '/admin/schedulers'
      fullPath: '/admin/schedulers'
      preLoaderRoute: typeof AuthenticatedAdminSchedulersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$slug': {
      id: '/_authenticated/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AuthenticatedProjectsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/channels': {
      id: '/_authenticated/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AuthenticatedSettingsChannelsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/memberships': {
      id: '/_authenticated/settings/memberships'
      path: '/memberships'
      fullPath: '/settings/memberships'
      preLoaderRoute: typeof AuthenticatedSettingsMembershipsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/projects': {
      id: '/_authenticated/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/runtime': {
      id: '/_authenticated/settings/runtime'
      path: '/runtime'
      fullPath: '/settings/runtime'
      preLoaderRoute: typeof AuthenticatedSettingsRuntimeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/projects/$slug/': {
      id: '/_authenticated/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof AuthenticatedProjectsSlugIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/agents': {
      id: '/_authenticated/projects/$slug/agents'
      path: '/agents'
      fullPath: '/projects/$slug/agents'
      preLoaderRoute: typeof AuthenticatedProjectsSlugAgentsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/audit': {
      id: '/_authenticated/projects/$slug/audit'
      path: '/audit'
      fullPath: '/projects/$slug/audit'
      preLoaderRoute: typeof AuthenticatedProjectsSlugAuditRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/automation': {
      id: '/_authenticated/projects/$slug/automation'
      path: '/automation'
      fullPath: '/projects/$slug/automation'
      preLoaderRoute: typeof AuthenticatedProjectsSlugAutomationRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/commands': {
      id: '/_authenticated/projects/$slug/commands'
      path: '/commands'
      fullPath: '/projects/$slug/commands'
      preLoaderRoute: typeof AuthenticatedProjectsSlugCommandsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/issues': {
      id: '/_authenticated/projects/$slug/issues'
      path: '/issues'
      fullPath: '/projects/$slug/issues'
      preLoaderRoute: typeof AuthenticatedProjectsSlugIssuesRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/queues': {
      id: '/_authenticated/projects/$slug/queues'
      path: '/queues'
      fullPath: '/projects/$slug/queues'
      preLoaderRoute: typeof AuthenticatedProjectsSlugQueuesRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/schedules': {
      id: '/_authenticated/projects/$slug/schedules'
      path: '/schedules'
      fullPath: '/projects/$slug/schedules'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSchedulesRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/settings': {
      id: '/_authenticated/projects/$slug/settings'
      path: '/settings'
      fullPath: '/projects/$slug/settings'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/tasks': {
      id: '/_authenticated/projects/$slug/tasks'
      path: '/tasks'
      fullPath: '/projects/$slug/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsSlugTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/trends': {
      id: '/_authenticated/projects/$slug/trends'
      path: '/trends'
      fullPath: '/projects/$slug/trends'
      preLoaderRoute: typeof AuthenticatedProjectsSlugTrendsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/workers': {
      id: '/_authenticated/projects/$slug/workers'
      path: '/workers'
      fullPath: '/projects/$slug/workers'
      preLoaderRoute: typeof AuthenticatedProjectsSlugWorkersRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/settings/notifications/': {
      id: '/_authenticated/settings/notifications/'
      path: '/'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsNotificationsRoute
    }
    '/_authenticated/settings/notifications/channels': {
      id: '/_authenticated/settings/notifications/channels'
      path: '/channels'
      fullPath: '/settings/notifications/channels'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsChannelsRouteImport
      parentRoute: typeof AuthenticatedSettingsNotificationsRoute
    }
    '/_authenticated/settings/notifications/deliveries': {
      id: '/_authenticated/settings/notifications/deliveries'
      path: '/deliveries'
      fullPath: '/settings/notifications/deliveries'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedSettingsNotificationsRoute
    }
    '/_authenticated/settings/notifications/subscriptions': {
      id: '/_authenticated/settings/notifications/subscriptions'
      path: '/subscriptions'
      fullPath: '/settings/notifications/subscriptions'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedSettingsNotificationsRoute
    }
    '/_authenticated/projects/$slug/schedules_/$scheduleId': {
      id: '/_authenticated/projects/$slug/schedules_/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/projects/$slug/schedules/$scheduleId'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSchedulesScheduleIdRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/schedules_/reconcile': {
      id: '/_authenticated/projects/$slug/schedules_/reconcile'
      path: '/schedules/reconcile'
      fullPath: '/projects/$slug/schedules/reconcile'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSchedulesReconcileRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/settings/': {
      id: '/_authenticated/projects/$slug/settings/'
      path: '/'
      fullPath: '/projects/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/settings/defaults': {
      id: '/_authenticated/projects/$slug/settings/defaults'
      path: '/defaults'
      fullPath: '/projects/$slug/settings/defaults'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsDefaultsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/settings/deliveries': {
      id: '/_authenticated/projects/$slug/settings/deliveries'
      path: '/deliveries'
      fullPath: '/projects/$slug/settings/deliveries'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/settings/members': {
      id: '/_authenticated/projects/$slug/settings/members'
      path: '/members'
      fullPath: '/projects/$slug/settings/members'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/settings/notifications': {
      id: '/_authenticated/projects/$slug/settings/notifications'
      path: '/notifications'
      fullPath: '/projects/$slug/settings/notifications'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/settings/providers': {
      id: '/_authenticated/projects/$slug/settings/providers'
      path: '/providers'
      fullPath: '/projects/$slug/settings/providers'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsRoute
    }
    '/_authenticated/projects/$slug/workers_/$workerId': {
      id: '/_authenticated/projects/$slug/workers_/$workerId'
      path: '/workers/$workerId'
      fullPath: '/projects/$slug/workers/$workerId'
      preLoaderRoute: typeof AuthenticatedProjectsSlugWorkersWorkerIdRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
    '/_authenticated/projects/$slug/settings/notifications/': {
      id: '/_authenticated/projects/$slug/settings/notifications/'
      path: '/'
      fullPath: '/projects/$slug/settings/notifications/'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRoute
    }
    '/_authenticated/projects/$slug/settings/notifications/channels': {
      id: '/_authenticated/projects/$slug/settings/notifications/channels'
      path: '/channels'
      fullPath: '/projects/$slug/settings/notifications/channels'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsChannelsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRoute
    }
    '/_authenticated/projects/$slug/settings/notifications/deliveries': {
      id: '/_authenticated/projects/$slug/settings/notifications/deliveries'
      path: '/deliveries'
      fullPath: '/projects/$slug/settings/notifications/deliveries'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRoute
    }
    '/_authenticated/projects/$slug/settings/notifications/subscriptions': {
      id: '/_authenticated/projects/$slug/settings/notifications/subscriptions'
      path: '/subscriptions'
      fullPath: '/projects/$slug/settings/notifications/subscriptions'
      preLoaderRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRoute
    }
    '/_authenticated/projects/$slug/tasks_/$engine/$taskId': {
      id: '/_authenticated/projects/$slug/tasks_/$engine/$taskId'
      path: '/tasks/$engine/$taskId'
      fullPath: '/projects/$slug/tasks/$engine/$taskId'
      preLoaderRoute: typeof AuthenticatedProjectsSlugTasksEngineTaskIdRouteImport
      parentRoute: typeof AuthenticatedProjectsSlugRoute
    }
  }
}

interface AuthenticatedSettingsNotificationsRouteChildren {
  AuthenticatedSettingsNotificationsChannelsRoute: typeof AuthenticatedSettingsNotificationsChannelsRoute
  AuthenticatedSettingsNotificationsDeliveriesRoute: typeof AuthenticatedSettingsNotificationsDeliveriesRoute
  AuthenticatedSettingsNotificationsSubscriptionsRoute: typeof AuthenticatedSettingsNotificationsSubscriptionsRoute
  AuthenticatedSettingsNotificationsIndexRoute: typeof AuthenticatedSettingsNotificationsIndexRoute
}

const AuthenticatedSettingsNotificationsRouteChildren: AuthenticatedSettingsNotificationsRouteChildren =
  {
    AuthenticatedSettingsNotificationsChannelsRoute:
      AuthenticatedSettingsNotificationsChannelsRoute,
    AuthenticatedSettingsNotificationsDeliveriesRoute:
      AuthenticatedSettingsNotificationsDeliveriesRoute,
    AuthenticatedSettingsNotificationsSubscriptionsRoute:
      AuthenticatedSettingsNotificationsSubscriptionsRoute,
    AuthenticatedSettingsNotificationsIndexRoute:
      AuthenticatedSettingsNotificationsIndexRoute,
  }

const AuthenticatedSettingsNotificationsRouteWithChildren =
  AuthenticatedSettingsNotificationsRoute._addFileChildren(
    AuthenticatedSettingsNotificationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsChannelsRoute: typeof AuthenticatedSettingsChannelsRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsMembershipsRoute: typeof AuthenticatedSettingsMembershipsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRouteWithChildren
  AuthenticatedSettingsProjectsRoute: typeof AuthenticatedSettingsProjectsRoute
  AuthenticatedSettingsRuntimeRoute: typeof AuthenticatedSettingsRuntimeRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsChannelsRoute: AuthenticatedSettingsChannelsRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsMembershipsRoute: AuthenticatedSettingsMembershipsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRouteWithChildren,
  AuthenticatedSettingsProjectsRoute: AuthenticatedSettingsProjectsRoute,
  AuthenticatedSettingsRuntimeRoute: AuthenticatedSettingsRuntimeRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedProjectsSlugSettingsNotificationsRouteChildren {
  AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute
  AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute
  AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute
  AuthenticatedProjectsSlugSettingsNotificationsIndexRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsIndexRoute
}

const AuthenticatedProjectsSlugSettingsNotificationsRouteChildren: AuthenticatedProjectsSlugSettingsNotificationsRouteChildren =
  {
    AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute:
      AuthenticatedProjectsSlugSettingsNotificationsChannelsRoute,
    AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute:
      AuthenticatedProjectsSlugSettingsNotificationsDeliveriesRoute,
    AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute:
      AuthenticatedProjectsSlugSettingsNotificationsSubscriptionsRoute,
    AuthenticatedProjectsSlugSettingsNotificationsIndexRoute:
      AuthenticatedProjectsSlugSettingsNotificationsIndexRoute,
  }

const AuthenticatedProjectsSlugSettingsNotificationsRouteWithChildren =
  AuthenticatedProjectsSlugSettingsNotificationsRoute._addFileChildren(
    AuthenticatedProjectsSlugSettingsNotificationsRouteChildren,
  )

interface AuthenticatedProjectsSlugSettingsRouteChildren {
  AuthenticatedProjectsSlugSettingsDefaultsRoute: typeof AuthenticatedProjectsSlugSettingsDefaultsRoute
  AuthenticatedProjectsSlugSettingsDeliveriesRoute: typeof AuthenticatedProjectsSlugSettingsDeliveriesRoute
  AuthenticatedProjectsSlugSettingsMembersRoute: typeof AuthenticatedProjectsSlugSettingsMembersRoute
  AuthenticatedProjectsSlugSettingsNotificationsRoute: typeof AuthenticatedProjectsSlugSettingsNotificationsRouteWithChildren
  AuthenticatedProjectsSlugSettingsProvidersRoute: typeof AuthenticatedProjectsSlugSettingsProvidersRoute
  AuthenticatedProjectsSlugSettingsIndexRoute: typeof AuthenticatedProjectsSlugSettingsIndexRoute
}

const AuthenticatedProjectsSlugSettingsRouteChildren: AuthenticatedProjectsSlugSettingsRouteChildren =
  {
    AuthenticatedProjectsSlugSettingsDefaultsRoute:
      AuthenticatedProjectsSlugSettingsDefaultsRoute,
    AuthenticatedProjectsSlugSettingsDeliveriesRoute:
      AuthenticatedProjectsSlugSettingsDeliveriesRoute,
    AuthenticatedProjectsSlugSettingsMembersRoute:
      AuthenticatedProjectsSlugSettingsMembersRoute,
    AuthenticatedProjectsSlugSettingsNotificationsRoute:
      AuthenticatedProjectsSlugSettingsNotificationsRouteWithChildren,
    AuthenticatedProjectsSlugSettingsProvidersRoute:
      AuthenticatedProjectsSlugSettingsProvidersRoute,
    AuthenticatedProjectsSlugSettingsIndexRoute:
      AuthenticatedProjectsSlugSettingsIndexRoute,
  }

const AuthenticatedProjectsSlugSettingsRouteWithChildren =
  AuthenticatedProjectsSlugSettingsRoute._addFileChildren(
    AuthenticatedProjectsSlugSettingsRouteChildren,
  )

interface AuthenticatedProjectsSlugRouteChildren {
  AuthenticatedProjectsSlugAgentsRoute: typeof AuthenticatedProjectsSlugAgentsRoute
  AuthenticatedProjectsSlugAuditRoute: typeof AuthenticatedProjectsSlugAuditRoute
  AuthenticatedProjectsSlugAutomationRoute: typeof AuthenticatedProjectsSlugAutomationRoute
  AuthenticatedProjectsSlugCommandsRoute: typeof AuthenticatedProjectsSlugCommandsRoute
  AuthenticatedProjectsSlugIssuesRoute: typeof AuthenticatedProjectsSlugIssuesRoute
  AuthenticatedProjectsSlugQueuesRoute: typeof AuthenticatedProjectsSlugQueuesRoute
  AuthenticatedProjectsSlugSchedulesRoute: typeof AuthenticatedProjectsSlugSchedulesRoute
  AuthenticatedProjectsSlugSettingsRoute: typeof AuthenticatedProjectsSlugSettingsRouteWithChildren
  AuthenticatedProjectsSlugTasksRoute: typeof AuthenticatedProjectsSlugTasksRoute
  AuthenticatedProjectsSlugTrendsRoute: typeof AuthenticatedProjectsSlugTrendsRoute
  AuthenticatedProjectsSlugWorkersRoute: typeof AuthenticatedProjectsSlugWorkersRoute
  AuthenticatedProjectsSlugIndexRoute: typeof AuthenticatedProjectsSlugIndexRoute
  AuthenticatedProjectsSlugSchedulesScheduleIdRoute: typeof AuthenticatedProjectsSlugSchedulesScheduleIdRoute
  AuthenticatedProjectsSlugSchedulesReconcileRoute: typeof AuthenticatedProjectsSlugSchedulesReconcileRoute
  AuthenticatedProjectsSlugWorkersWorkerIdRoute: typeof AuthenticatedProjectsSlugWorkersWorkerIdRoute
  AuthenticatedProjectsSlugTasksEngineTaskIdRoute: typeof AuthenticatedProjectsSlugTasksEngineTaskIdRoute
}

const AuthenticatedProjectsSlugRouteChildren: AuthenticatedProjectsSlugRouteChildren =
  {
    AuthenticatedProjectsSlugAgentsRoute: AuthenticatedProjectsSlugAgentsRoute,
    AuthenticatedProjectsSlugAuditRoute: AuthenticatedProjectsSlugAuditRoute,
    AuthenticatedProjectsSlugAutomationRoute:
      AuthenticatedProjectsSlugAutomationRoute,
    AuthenticatedProjectsSlugCommandsRoute:
      AuthenticatedProjectsSlugCommandsRoute,
    AuthenticatedProjectsSlugIssuesRoute: AuthenticatedProjectsSlugIssuesRoute,
    AuthenticatedProjectsSlugQueuesRoute: AuthenticatedProjectsSlugQueuesRoute,
    AuthenticatedProjectsSlugSchedulesRoute:
      AuthenticatedProjectsSlugSchedulesRoute,
    AuthenticatedProjectsSlugSettingsRoute:
      AuthenticatedProjectsSlugSettingsRouteWithChildren,
    AuthenticatedProjectsSlugTasksRoute: AuthenticatedProjectsSlugTasksRoute,
    AuthenticatedProjectsSlugTrendsRoute: AuthenticatedProjectsSlugTrendsRoute,
    AuthenticatedProjectsSlugWorkersRoute:
      AuthenticatedProjectsSlugWorkersRoute,
    AuthenticatedProjectsSlugIndexRoute: AuthenticatedProjectsSlugIndexRoute,
    AuthenticatedProjectsSlugSchedulesScheduleIdRoute:
      AuthenticatedProjectsSlugSchedulesScheduleIdRoute,
    AuthenticatedProjectsSlugSchedulesReconcileRoute:
      AuthenticatedProjectsSlugSchedulesReconcileRoute,
    AuthenticatedProjectsSlugWorkersWorkerIdRoute:
      AuthenticatedProjectsSlugWorkersWorkerIdRoute,
    AuthenticatedProjectsSlugTasksEngineTaskIdRoute:
      AuthenticatedProjectsSlugTasksEngineTaskIdRoute,
  }

const AuthenticatedProjectsSlugRouteWithChildren =
  AuthenticatedProjectsSlugRoute._addFileChildren(
    AuthenticatedProjectsSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedAdminSchedulersRoute: typeof AuthenticatedAdminSchedulersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedProjectsSlugRoute: typeof AuthenticatedProjectsSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedAdminSchedulersRoute: AuthenticatedAdminSchedulersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedProjectsSlugRoute: AuthenticatedProjectsSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  LoginMfaRoute: LoginMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
